apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.appName }}
    
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        paths:
          - /var/log/containers/*.log
        json.keys_under_root: false
        json.overwrite_keys: false

    setup.dashboards.enabled: false
    setup.ilm.enabled: false
    setup.template.name: "filebeat"
    setup.template.pattern: "filebeat-*"

    output.elasticsearch:
      hosts: ["{{ .Values.esService }}"]